---
title: "Universidad Regional Amazónica Ikiam"
author: "Tanya Michelle Camalle Valverde1" and "Francisco Javier Mendoza"
date: "2023-03-17"
subtitle: ' Analisis del examen Ser Bachiller de Factores Asociados 2018-2019'
mail: tanya,camalle@est.ikiam.edu.ec
output: html_document
    df_print: paged
---

## #Resumen

##Introducción

##Metodología

```{r}

```

###Resultados y Discusión

```{r setup, include=FALSE}
#Tabla de datos con los que se va a trabajar
library(readxl)
SBAC19_micro <- read_excel("C:/Users/USER/Desktop/SBAC19_micro.xlsx")
View(SBAC19_micro)

#Función select, dplyr y devtools para separar los datos a utilizar
#install.packages("dplyr")
library(dplyr)
#install.packages(devtools)
install.packages("devtools")
library(devtools)

#install.packages(tidyverse)
library(tidyverse)

#selección de datos
SBAC19_micro %>% 
  filter(region== '2')

SBAC19_micro %>% 
  filter(zona== '3')

mat<- list(imat = c(0,1,2),
          B = data.frame(matematica = 3, nivel = c(0,1,2)))
mat

ling<- list(ilyl = c(0,1,2),
          D = data.frame(linguistica = 3, nivel = c(0,1,2)))
ling

cient<- list(icn = c(0,1,2),
          E = data.frame(cientifico = 3, nivel = c(0,1,2)))
cient

social<- list(ies = c(0,1,2),
          G = data.frame(social = 3, nivel = c(0,1,2)))
social


#Grafico de notas de matematicas del Examen Ser Bachiller (INEVAL)
library(readxl)
SBAC19_micro <- read_excel("C:/Users/USER/Desktop/SBAC19_micro.xlsx")
barplot(prop.table(table(SBAC19_micro$imat)),col=c("orange","blue", "purple"),
        legend.text=c("0","1","2"),ylim=c(0,0.8),main="Notas de matematica del examen Ser bachiller",          
        xlab="Matematicas",                   
        ylab="Notas")

#Grafico de calificaciones del Examen Ser Bachiller (INEVAL)
library(dplyr)
library(ggplot2)
ggplot(SBAC19_micro, aes(inev)) +
  geom_bar(fill="#69b3a2",
    size = 2)+
labs(title = "Calificaciones INEVAL",
       x ="Notas INEVAL",
       y = "Calificación")+
  scale_x_discrete(labels = c(7.95,6.79,6.91,7.9,6.85,7.07,7.12,7.44,6.3,8.53,6.46,7.52,7.1,7.98,7.95,7.61,8.33,8.07,7.67,7.58,7.39,6.63,7.27,7.4,6.89,6.09,6.94,5.82,7.41,6.41,6.52,6.41,7.72,7.29,7.81,7.61,7.81,7.53,7.72,7.38,7.84,8.13,8.01,7.61,7.3,7.66,6.86,7.81,7.3,7.78))+ theme(axis.text.x = element_text(angle=90)) 

#Regresion lineal de notas Examen Ser Bachiller (INEVAL) en la categoria social
library(ggplot2)
  ggplot(SBAC19_micro,aes(x=ies, y=inev)) +
  geom_smooth(method="lm", formula=y~x, se=FALSE, color="dodgerblue1") +
  geom_segment(aes(xend=ies, yend=inev), col='blue', lty='dashed') +
    geom_point() +
  geom_point(aes(y=inev), col='orange') +
  theme_light()+
    labs(title = "Calificaciones INEVAL en la categoria social",
       x ="Notas INEVAL",
       y = "Calificación categoria social")
    

```

```{r setup, include=FALSE}

```

##Conclusión

##Bibliografía

```{r setup, include=FALSE}
  
```
